import type { NextPage } from 'next';
import Head from 'next/head';
import { usePhantom } from '@dobosmarton/phantom-hook';
import { ConnectWallet } from '../src/components/buttons/connectWallet';
import { Footer } from '../src/components/footer/footer';
import { CandyMachine } from '../src/components/candyMachine/candyMachine';
import { ExtendedWindow } from '../src/services/solana';

const Home: NextPage = () => {
  const { walletAddress, connectWallet } = usePhantom();

  return (
    <>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="max-w-7xl mx-auto sm:px-6 lg:px-8">
          <div className="flex justify-center pt-20">
            <div>
              <div className="flex flex-col items-center">
                <p className="text-2xl font-bold my-4">🍭 Candy Drop</p>
                <p className="sub-text my-4">NFT drop machine with fair mint</p>
                {!walletAddress && <ConnectWallet onClick={connectWallet} />}

                {walletAddress && <CandyMachine walletAddress={(window as ExtendedWindow).solana} />}
              </div>
            </div>
          </div>
        </main>

        <Footer />
      </div>
    </>
  );
};

export default Home;
